FROM node:alpine

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]

#docker build -f Dockerfile.dev -t ilyanesterow/silver-client .
#docker run -v /app/node_modules -v $(pwd):/app -p 3000:3000 ilyanesterow/silver-client